### PR TITLE
Bump minimum python to 3.9

### LINKED ISSUE #484: [BUG] v0.7.0 dropped python 3.8 ?
**What happened**:

I was unable to install xgcm version 0.7.0 with python 3.8

**What you expected to happen**:
As xarray is still supporting python 3.8, I was expecting to be able to install xgcm 0.7.0

As it is not written in the what's new, I guess that dropping python 3.8 may be an error? (or otherwise, it should probably be written in the what's new)

### PR DESCRIPTION
**Pull request by TomNicholas**
To close https://github.com/xgcm/xgcm/issues/484#issuecomment-1105329523

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rabernat** [comment]
I think you need to bump the build number, no?

**Comment by TomNicholas** [comment]
Not sure - I've never altered a feedstock before

**Comment by jbusecke** [comment]
Just bumped the build to 1

**Comment by TomNicholas** [comment]
Thank you @jbusecke !

Do I have to do anything else now? If not then can someone merge this please? (I don't have merge access to this repo)

**Pull request merged**
